# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: itopchu <itopchu@student.codam.nl>           +#+                      #
#                                                    +#+                       #
#    Created: 2023/01/22 15:14:44 by itopchu        #+#    #+#                 #
#    Updated: 2023/01/22 15:14:44 by itopchu       ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

NAME	= printf
HEADER	= ../header/
ARCHIVE_NAME = $(NAME).a
# **************************************************************************** #
CC		= gcc
CFLAGS	= -Wall -Wextra -Werror
COMPILE = $(CC) $(CFLAGS) -I $(HEADER)
RM		= rm -rf
# **************************************************************************** #
AR		= ar
ARFLAGS	= -rcs
ARCHIVE	= $(AR) $(ARFLAGS)
# **************************************************************************** #
DIR_OBJ	= ../../obj/
# **************************************************************************** #
SRC		=	base_conv.c \
			based_int.c \
			ft_printf.c \
			hex.c \
			write.c
# **************************************************************************** #
OBJ		= $(SRC:%.c=$(DIR_OBJ)%.o)
# **************************************************************************** #
$(DIR_OBJ)%.o: %.c $(HEADER)
	@$(COMPILE) -o $@ -c $<

$(ARCHIVE_NAME): $(OBJ)
	@$(ARCHIVE) $(ARCHIVE_NAME) $(OBJ)
	@echo "$(NAME) is compiled."
# **************************************************************************** #
all: $(ARCHIVE_NAME)

fclean:
	@$(RM) $(ARCHIVE_NAME)
	@echo "$(ARCHIVE_NAME) is removed"

re: fclean all

.PHONY: clean all fclean re